### ISSUE TITLE
 ERROR #11321  PLUGIN After update to 7.6.0

### ISSUE THREAD

**Issue by Muata** [sanity-io/gatsby-source-sanity#200]
```
 ERROR #11321  PLUGIN

"gatsby-source-sanity" threw an error while running the sourceNodes lifecycle:

Unexpected token ▼ in JSON at position 0



  SyntaxError: Unexpected token ▼ in JSON at position 0

  - Transform.parse [as mapper]

  - index.js:44 Transform.transform [as _transform]
    [lempiank-blog]/[split2]/index.js:44:23

  - transform:175 Transform._write
    node:internal/streams/transform:175:8

  - writable:392 writeOrBuffer
    node:internal/streams/writable:392:12

  - writable:333 _write
    node:internal/streams/writable:333:10

  - writable:337 Transform.Writable.write
    node:internal/streams/writable:337:10

  - readable:766 IncomingMessage.ondata
    node:internal/streams/readable:766:22

  - node:events:513 IncomingMessage.emit
    node:events:513:28

  - readable:539 IncomingMessage.Readable.read
    node:internal/streams/readable:539:10

  - readable:1023 flow
    node:internal/streams/readable:1023:34

  - readable:1004 resume_
    node:internal/streams/readable:1004:3

  - task_queues:82 processTicksAndRejections
    node:internal/process/task_queues:82:21


warn The gatsby-source-sanity plugin has generated no Gatsby nodes. Do you need it? This could also suggest the plugin
is misconfigured.
```

Gatsby 5.1.0 and all it's plugins updated to this version.
Working with 7.5.1

**Comment by hayzey** [comment]
I'm experiencing the same issue after upgrading to Gatsby 5. I did some digging and it seems that at one point, a raw data stream is being passed into `JSON.parse`, rather than a readable chunk of JSON from that stream.

This file seems to be where the error is thrown in my build. Looks like `split` is passing data to that `JSON.parse` callback.

https://github.com/sanity-io/gatsby-source-sanity/blob/3b959b0d430fe20152974f9898fb7bf2b2374874/src/util/getAllDocuments.ts#L17

That data seems to come from `getDocumenStream`. I console logged that data and it looks like binary data, not JSON.

https://github.com/sanity-io/gatsby-source-sanity/blob/3b959b0d430fe20152974f9898fb7bf2b2374874/src/util/getDocumentStream.ts#L6

**Comment by hayzey** [comment]
I don't understand this codebase enough to go any deeper on this, but it seems that the issue is related to the data stream not being converted into readable JSON before it's passed into `JSON.parse`.

**Comment by amcc** [comment]
i have the same issue - new gatsby 5 site installed with `npm init gatsby` 

I then cloned a known working gatsby 4 site and did a `npm i` and got the same issue, so i assumed it might be a node 18 issue (i was previously using 16).

I switched to node v16 and still have the same issue.

I have these warnings when installing the modules. It looks like it might be to do with the sanity plugin update and not to do with gatsby v5 directly:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: gatsby-plugin-utils@4.2.0
npm WARN Found: gatsby@4.24.8
npm WARN node_modules/gatsby
npm WARN   gatsby@"^4.3.0" from the root project
npm WARN   16 more (babel-plugin-remove-graphql-queries, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer gatsby@"^5.0.0-next" from gatsby-plugin-utils@4.2.0
npm WARN node_modules/gatsby-source-sanity/node_modules/gatsby-plugin-utils
npm WARN   gatsby-plugin-utils@"^4.1.0" from gatsby-source-sanity@7.6.0
npm WARN   node_modules/gatsby-source-sanity
npm WARN 
npm WARN Conflicting peer dependency: gatsby@5.2.0
npm WARN node_modules/gatsby
npm WARN   peer gatsby@"^5.0.0-next" from gatsby-plugin-utils@4.2.0
npm WARN   node_modules/gatsby-source-sanity/node_modules/gatsby-plugin-utils
npm WARN     gatsby-plugin-utils@"^4.1.0" from gatsby-source-sanity@7.6.0
npm WARN     node_modules/gatsby-source-sanity
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN Found: react@17.0.2
npm WARN node_modules/react
npm WARN   react@"^17.0.1" from the root project
npm WARN   17 more (@gatsbyjs/reach-router, @loadable/component, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/gatsby/node_modules/react-server-dom-webpack
npm WARN   react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.24.8
npm WARN   node_modules/gatsby
npm WARN 
npm WARN Conflicting peer dependency: react@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN   node_modules/gatsby/node_modules/react-server-dom-webpack
npm WARN     react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.24.8
npm WARN     node_modules/gatsby
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'gatsby-core-utils@4.2.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'gatsby-plugin-utils@4.2.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'gatsby-sharp@1.2.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```

However I then tried locking gatsby-source-sanity to 7.3.2 and that came up with the same error too.

**Comment by pierrenel** [comment]
Seeing this too, fresh install.

```"gatsby-source-sanity" threw an error while running the sourceNodes lifecycle:

Unexpected token  in JSON at position 0



  SyntaxError: Unexpected token  in JSON at position 0

  - Transform.parse [as mapper]

  - index.js:44 Transform.transform [as _transform]
    [gatsby]/[split2]/index.js:44:23

  - transform:175 Transform._write
    node:internal/streams/transform:175:8

  - writable:392 writeOrBuffer
    node:internal/streams/writable:392:12

  - writable:333 _write
    node:internal/streams/writable:333:10

  - writable:337 Transform.Writable.write
    node:internal/streams/writable:337:10

  - readable:766 IncomingMessage.ondata
    node:internal/streams/readable:766:22

  - node:events:513 IncomingMessage.emit
    node:events:513:28

  - readable:539 IncomingMessage.Readable.read
    node:internal/streams/readable:539:10

  - readable:1023 flow
    node:internal/streams/readable:1023:34

  - readable:1004 resume_
    node:internal/streams/readable:1004:3

  - task_queues:82 processTicksAndRejections
    node:internal/process/task_queues:82:21


warn The gatsby-source-sanity plugin has generated no Gatsby nodes. Do you need it? This could also
suggest the plugin is misconfigured.
```

**Comment by chrispecoraro** [comment]
@mcollina may know something..looks like his code.

**Comment by roffelsaurus** [comment]
Also experience same stack trace error, but I have not migrated to gatsby v5 yet. 

I also had not updated to 7.6.0 explicitly, but got it using npm "^7.4.2" which then takes 7.6.0 as a new minor release. So poor semver choice even if this turns out to be just a bug and it supposedly should have had backwards compatibility.

**Comment by mtt786** [comment]
I fixed this by doing these two steps in gatsby 4 but still no fixes found for gatsby 5:
- npm remove gatsby-source-sanity
- npm i gatsby-source-sanity@7.5.1 -S

**Comment by Mcdonamj087** [comment]
I see this too - though interestingly it doesn't seem to happen with a clean javascript setup.  Only happens when running typescript gatsby.  See my stackoverflow for more details. https://stackoverflow.com/questions/74690164/gatsby-source-sanity-error-while-running-the-sourcenodes-lifecycle-with-typesc

**Comment by paulwhitaker** [comment]
Bump... I am experiencing the same when I attempt to upgrade the source plugin.
- Gatsby 5
- Typescript
- Studio V3

**Comment by Mcdonamj087** [comment]
> Bump... I am experiencing the same when I attempt to upgrade the source plugin.
> 
> * Gatsby 5
> * Typescript
> * Studio V3

Curious, what versions of everything are you running?  U mind sharing your deps list?  I tried simply downgrading gatsby-source-sanity, but it was still failing.  Had to downgrade Gatsby to v4 and a suite of other dependencies, but missing out on those new v5 enhancements!

**Comment by paulwhitaker** [comment]
This may go... "Spooky Quite" I just upgraded and it worked. Of course v3 officially released now and I think gatsby went from 5.1 to 5.2. But here's a snapshop of the relevant node modules.

```json
"dependencies": {
...
    "@portabletext/react": "^2.0.0",
    "@sanity/client": "^3.3.2",
    "axios": "^1.2.1",,
    "gatsby": "^5.2.0",
    "gatsby-plugin-image": "3.2.0",
    "gatsby-plugin-netlify": "^5.0.0",
    "gatsby-plugin-sanity-image": "^0.13.3",
    "gatsby-source-sanity": "7.6.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
...
  },
```

**Comment by LekoArts** [comment]
Please note that this issue is unrelated to Gatsby 5 and was caused by a `axios` bump and should be fixed once https://github.com/sanity-io/gatsby-source-sanity/pull/207 is merged and released.
